Repository splendid-pdf/yandex-market, pull requests merged in 2022-12, with the labels that each got.

#11 feature/add update shop system
  shopsystem-service/.gitignore
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/ShopSystemController.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/ShopSystemControllerAdvice.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/LocationDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/ShopSystemDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/shop/Location.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/ExceptionResponse.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/ShopSystemService.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
  shopsystem-service/src/main/resources/application.yaml
  shopsystem-service/src/main/resources/db/migration/V1_Create_shop_system_table.sql
Labels: enhancement

#10 add open api spec to user info
  user-info-service/build.gradle
  user-info-service/openapi/docs/spec.yaml
  user-info-service/src/main/java/com/market/userinfoservice/model/Sex.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/UserInfoServiceApplication.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserController.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/Contact.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/Location.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/NotificationSettings.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/Sex.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/SocialNetwork.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/User.java
Labels: documentation

#15 feature/add create branch shop system
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/ShopSystemControllerAdvice.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/shop/ShopSystemController.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/SupportDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/BranchDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/ContactDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/shop/ShopSystemRequestDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/shop/ShopSystemResponsesDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/shop/SupportDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/extensions/ShopSystemExtensionHandler.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/branch/Delivery.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/shop/ShopSystem.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/ExceptionResponse.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/BranchService.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/impl/ShopSystemService.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/shop/ShopSystemService.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/shop/impl/ShopSystemServiceImpl.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
  shopsystem-service/src/main/resources/application.yaml
Labels: enhancement

#16 Добавил возможность обновления отдела по внешнему ID. Также незначита…
  shopsystem-service/build.gradle
  shopsystem-service/docker-compose.yaml
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/branch/BranchController.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/shop/ShopSystemController.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/branch/Branch.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/repositories/BranchRepository.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/BranchService.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/shop/ShopSystemService.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/shop/impl/ShopSystemServiceImpl.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
  shopsystem-service/src/main/resources/application.yaml
  shopsystem-service/src/main/resources/db/tests/TEST_INSERT.SQL
Labels: enhancement

#17 feature/add exception handler for branch registration
  shopsystem-service/src/main/java/com/yandex/market/shopservice/controllers/ShopSystemControllerAdvice.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/LocationDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/BranchDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/ContactDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryIntervalDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/dto/branch/DeliveryZoneDto.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/Location.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/branch/Branch.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/shop/ShopSystem.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/ExceptionResponse.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
  shopsystem-service/src/main/resources/db/migration/V1_Create_branch_table.sql
Labels: enhancement

#19 feature/fixed compile errors
  shopsystem-service/src/main/java/com/yandex/market/shopservice/model/branch/Branch.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/service/branch/impl/BranchServiceImpl.java
  shopsystem-service/src/main/java/com/yandex/market/shopservice/util/ShopSystemMapper.java
Labels: bug

#9 Add crud operations to user-info
  user-info-service/build.gradle
  user-info-service/openapi/docs/spec.yaml
  user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserController.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/controller/UserControllerAdvice.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/dto/UserDto.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/mapper/BiMapper.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/mapper/ContactMapper.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/mapper/LocationMapper.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/mapper/Mapper.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/mapper/UserMapper.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/Location.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/NotificationSettings.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/model/User.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/repository/UserRepository.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/response/ExceptionResponse.java
  user-info-service/src/main/java/com/yandex/market/userinfoservice/service/UserService.java
  user-info-service/src/main/resources/application.yaml
Labels: enhancement
